config/routes.rb
Church::Application.routes.draw do
  devise_for :users, path_names: {sign_in: 'login', sign_out: 'logout'}, :controllers => { :registrations => "users" }


  mount Ckeditor::Engine => '/ckeditor'

	# mount Ckeditor::Engine => '/ckeditor'
  # match "users/search", :to => "users#search"
  devise_scope :user do  
    match "/users/search" => "users#search" 
    match "/users" => "users#index"
    match "users/:id/user_prayer_list", :to => "users#user_prayer_list", :as => "user_prayer_list"
    resources :users
  end
  resources :roles
  resources :users do 
    collection { post :sort }
  end
  resources :profiles
  resources :links
  resources :partials
  resources :categories
  resources :prayers 
  resources :affiliations
  resources :references
  resources :scriptures



  #partials
  match "announcement_partial", :to => "announcements#announcement_partial"
  match "blog_partial", :to => "blogs#blog_partial"
  match "event_partial", :to => "events#event_partial"
  match "prayer_partial", :to => "prayers#prayer_partial"


  # announcements
  match 'announcements/:id/hide', to: 'announcements#hide', as: 'hide_announcement'
  resources :announcements do
    collection { post :sort }
  end
  match "announcements/:id/announcement_status", to: "announcements#announcement_status", as: "announcement_status"
  match "announcements/:id/announcement_starts_at", to: "announcements#announcement_starts_at", as: "announcement_starts_at"
  match "announcements/:id/announcement_ends_at", to: "announcements#announcement_ends_at", as: "announcement_ends_at"
  
  # blogs
  resources :blogs do
    resources :comments
    collection { post :sort }
  end
  match 'blogs/:id/blog_status', to: 'blogs#blog_status', as: 'blog_status'
  match "blogs/:id/blog_starts_at", to: "blogs#blog_starts_at", as: "blog_starts_at"
  match "blogs/:id/blog_ends_at", to: "blogs#blog_ends_at", as: "blog_ends_at"
  
  # events
  resources :events do
    collection { post :sort }
  end
  match 'events/:id/event_status', to: 'events#event_status', as: 'event_status'
  match "events/:id/event_starts_at", to: "events#event_starts_at", as: "event_starts_at"
  match "events/:id/event_ends_at", to: "events#event_ends_at", as: "event_ends_at"

  # pages
  resources :pages do
    collection { post :sort }
    member { put :link, :status }
  end
  # match 'pages/:id/status', to: 'pages#status', as: 'status'

  # supermodels
  resources :supermodels do
    collection { post :sort }
  end
  match "supermodels/:id/model_status", :to => "supermodels#model_status", :as => "model_status"

  match 'dashboard', :to => 'static_pages#dashboard'
  
  root :to => "pages#show", :id => 'home'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :blog_id, :body, :email, :name
  validates_presence_of :body
  belongs_to :blog

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  load_and_authorize_resource
  def index
    @comments = Comment.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @comments }
    end
  end


  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @comment }
    end
  end


  def new
    @comment = Comment.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @comment }
    end
  end


  def edit

  end


def create
    @blog = Blog.find(params[:blog_id])
    @comment = @blog.comments.build(params[:comment])
    respond_to do |format|
      if @comment.save
        format.html { redirect_to(@blog, :notice => 'Comment was successfully created.') }
        format.xml  { render :xml => @blog, :status => :created, :location => @blog }
      else
        format.html { redirect_to(@blog, :notice => 
        'Comment could not be saved. Please fill in all fields')}
        format.xml  { render :xml => @comment.errors, :status => :unprocessable_entity }
      end
    end
  end


  def update
    @blog = @comment.blog
    respond_to do |format|
      if @comment.update_attributes(params[:comment])
        format.html { redirect_to(@blog, :notice => 'Comment was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @comment.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to blogs_url }
      format.json { head :no_content }
    end
  end
end

app/views/comments/_comment.html.erb
<% if comment.body %>
  <div class="comment">
    <p class="author"><b><%= comment.name %></b>said:</p>
    <%= content_tag :p, comment.body %>
    <%= link_to 'Edit | ', [@blog, comment]  if can? :edit, comment %>
    <%= link_to 'Delete', [@blog, comment], :confirm => 'Are you sure?', :method => :delete if can? :edit, comment %>
  </div>
<% end %>

app/views/comments/_form.html.erb
<%= form_for [@blog, @comment] do |f| %> 
  <%= render 'shared/errors', object: @comment %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <tr>
    <th>Blog</th>
    <th>Name</th>
    <th>Email</th>
    <th>Body</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @comments.each do |comment| %>
  <tr>
    <td><%= comment.blog_id %></td>
    <td><%= comment.name %></td>
    <td><%= comment.email %></td>
    <td><%= comment.body %></td>
    <td><%= link_to 'Show', comment %></td>
    <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
    <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<% div_for comment do %>
  <p>
    <b>Name:</b>
    <%= comment.name %>
  </p>

  <p>
    <b>Email:</b>
    <%= comment.email %>
  </p>

  <p>
    <b>Comment:</b>
    <%= comment.body %>
  </p>

<%= link_to 'Edit', edit_article_comment_path(@article, comment) %> |
<%= link_to 'Delete', article_comment_path(@article, comment), :confirm => 'Are you sure?', :method => :delete %>
<% end %>