config/routes.rb
Church::Application.routes.draw do
  devise_for :users, path_names: {sign_in: 'login', sign_out: 'logout'}, :controllers => { :registrations => "users" }


  mount Ckeditor::Engine => '/ckeditor'

	# mount Ckeditor::Engine => '/ckeditor'
  # match "users/search", :to => "users#search"
  devise_scope :user do  
    match "/users/search" => "users#search" 
    match "/users" => "users#index"
    match "users/:id/user_prayer_list", :to => "users#user_prayer_list", :as => "user_prayer_list"
    resources :users
  end
  resources :roles
  resources :users do 
    collection { post :sort }
  end
  resources :profiles
  resources :links
  resources :partials
  resources :categories
  resources :prayers 
  resources :affiliations
  resources :references
  resources :scriptures



  #partials
  match "announcement_partial", :to => "announcements#announcement_partial"
  match "blog_partial", :to => "blogs#blog_partial"
  match "event_partial", :to => "events#event_partial"
  match "prayer_partial", :to => "prayers#prayer_partial"


  # announcements
  match 'announcements/:id/hide', to: 'announcements#hide', as: 'hide_announcement'
  resources :announcements do
    collection { post :sort }
  end
  match "announcements/:id/announcement_status", to: "announcements#announcement_status", as: "announcement_status"
  match "announcements/:id/announcement_starts_at", to: "announcements#announcement_starts_at", as: "announcement_starts_at"
  match "announcements/:id/announcement_ends_at", to: "announcements#announcement_ends_at", as: "announcement_ends_at"
  
  # blogs
  resources :blogs do
    resources :comments
    collection { post :sort }
  end
  match 'blogs/:id/blog_status', to: 'blogs#blog_status', as: 'blog_status'
  match "blogs/:id/blog_starts_at", to: "blogs#blog_starts_at", as: "blog_starts_at"
  match "blogs/:id/blog_ends_at", to: "blogs#blog_ends_at", as: "blog_ends_at"
  
  # events
  resources :events do
    collection { post :sort }
  end
  match 'events/:id/event_status', to: 'events#event_status', as: 'event_status'
  match "events/:id/event_starts_at", to: "events#event_starts_at", as: "event_starts_at"
  match "events/:id/event_ends_at", to: "events#event_ends_at", as: "event_ends_at"

  # pages
  resources :pages do
    collection { post :sort }
    member { put :link, :status }
  end
  # match 'pages/:id/status', to: 'pages#status', as: 'status'

  # supermodels
  resources :supermodels do
    collection { post :sort }
  end
  match "supermodels/:id/model_status", :to => "supermodels#model_status", :as => "model_status"

  match 'dashboard', :to => 'static_pages#dashboard'
  
  root :to => "pages#show", :id => 'home'
end

app/views/shared/_affiliation.html.erb
<!--    
Intercessor new
Prayer_req new
Choose affiliation.  If user's church is not in list, user can add his/her church
	user will also add city and state.
	New church will save to database prior to intercessor/prayer_req saving
	User now belongs to affiliation
-->

<%= f.label :affiliation, "What church do you belong to?" %> <br />  
<%= f.collection_select :affiliation, Affiliation.where(approved: true), :id, :church, prompt: "no current affiliation" %>
<div class="add_your_church" ><em>Not listed? <span>Click here</span> to add your church.</em></div>
<div id="new_church_name" class="hidden">
	<%= f.label :new_church_name, "Name of church" %>
	<%= f.text_field :new_church_name %><%= required_field %><br />
	<%= f.label :church_city, "City" %>
	<%= f.text_field :church_city %><%= required_field %><br />
	<%= f.label :church_state, "State" %>
	<%= f.select(:church_state, Arrays::STATES, { prompt: true }) %><%= required_field %>
</div>

app/views/shared/_announcements.html.erb
<% Announcement.current(cookies.signed[:hidden_announcement_ids]).each do |announcement| %>
  <%= div_for announcement do %>
    <%= announcement.message %>
    <%= link_to "hide announcement", hide_announcement_path(announcement), remote: true %>
  <% end %>
<% end %>

app/views/shared/_authentication.html.erb
<div class="field"> 
    <%= f.label :fullname %><%= required_field %><br />
    <%= f.text_field :fullname %>
</div>
<div class="field"> 
    <%= f.label :email %><%= required_field %><br />
    <%= f.text_field :email %>
</div>
<div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
</div>
<div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
</div>

app/views/shared/_crud_btns.html.erb
<ul class="crud_buttons">
	<% if object.class.name == "Category" %>
		<% klass = "categorie" %>
	<% else %>
 		<% klass = object.class.name.downcase %>
 	<% end %>
	<% modelK = object.class.name.classify.constantize %>
	<%= content_tag :li, link_to("edit", "#{klass}s/#{object.id}/edit"), class: "edit" if can? :update, modelK %>
	<%= content_tag :li, link_to("view", "#{klass}s/#{object.id}"), class: "view" if can? :show, modelK%>
	<%= content_tag :li, link_to("delete", "#{klass}s/#{object.id}", :confirm => "are you sure?", :method => :delete ), class: "delete" if can? :delete, modelK %>
	
</ul>

app/views/shared/_crud_btns_without_view.html.erb
<ul class="crud_buttons">
	<% if object.class.name == "Category" %>
		<% klass = "categorie" %>
	<% else %>
 		<% klass = object.class.name.downcase %>
 	<% end %>
 	<% modelK = object.class.name.classify.constantize %>
	<%= content_tag :li, link_to("edit", "#{klass}s/#{object.id}/edit"), class: "edit" if can? :update, modelK  %>
	<%= content_tag :li, link_to("delete", "#{klass}s/#{object.id}", :confirm => "are you sure?", :method => :delete ), class: "delete" if can? :delete, modelK %>
</ul>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
	<div id="error_explanation">
		
		<h2><%= pluralize(object.errors.count, "error") %>
			prohibited this <%= object.class.to_s.underscore.humanize.downcase %>
			from being saved:</h2>
		<p>There were problems with the following fields:</p>
		<ul>
			<% object.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
		</ul>
		
	</div>
<% end %>

app/views/shared/_flash_messages.html.erb
<div id="flash_messages">
  <% flash.each do |key, value| %>
    <%= content_tag(:div, value, :class => "flash #{key}") %>
  <% end %>
</div>

app/views/shared/_footer.html.erb
<div class="full-width" id="footer">
	<div class="container">
		<ul class="right">
		  
	      <% if current_user %>
	          <%= content_tag :li, link_to("Logout", destroy_user_session_path, :method => :delete) %>
	      <% else %>
	          <%= content_tag :li, link_to("Sign In", new_user_session_path) %>
	      <% end %>
    	</ul>
		
	</div>
</div>	

app/views/shared/_header.html.erb
<div class="full-width" id="top-nav">
  <div class="container">
    <ul class="right"> 
      <% if user_signed_in? %>
            <%= content_tag :li, link_to("Dashboard", dashboard_path) if (current_user.role_ids & [1,2]).length > 0 %>
            <%= link_to content_tag(:li, "Welcome, #{current_user.first_name}"), user_path(current_user), class: "user_name" %>
      <% end %>
    </ul>
     
    <ul class="left">
      <% @pages = Describe.new(Page).published.order("position ASC") %>
      <% top_link = Link.find_by_location("top_link").id %>
      <% @pages.each do |page| %>
        <% if page.link_ids.include?(top_link) %>
          <%= content_tag :li, link_to(page.title, [page]) %>
        <% end %>
      <% end %>
       
    </ul>
    
   <ul class="right">
      <% if current_user %>
          <%= content_tag :li, link_to("Logout", destroy_user_session_path, :method => :delete) %>
      <% else %>
          <%= content_tag :li, link_to("Create an Account", new_user_registration_path) %>
          <%= content_tag :li, link_to("Sign In", new_user_session_path) %>
      <% end %>
    </ul>
    <br class="clear"/>
  </div>
</div>

app/views/shared/_sidebar.html.erb
<% content_for :sidebar do %>

	<div class="sidebar">
		<div class="prayer_band">
		  <h2>Request Prayer</h2>
		</div>

		<!-- prayer request form -->
		<div class="col1">
		 	<div class="side_table">
		   	<%= render 'prayers/form' %>
		 	</div>
		</div>

		<!-- all other partials -->
		<% Partial.all.each do |partial| %>
			<% if @page %>
				<% if @page.partial_ids.include?(partial.id) %>
					<% prayer = Partial.find_by_name("Prayer").id %>
					<% unless partial.id == prayer %>
						<div class="col1">
				 			<div class="side_table">
								<%= render "#{partial.name.downcase}s/#{partial.name.downcase}_partial" %>
							</div>
						</div>
					<% end %>
				<% end %>
			<% else %>
				<% prayer = Partial.find_by_name("Prayer").id %>
					<% unless partial.id == prayer %>
						<div class="col1">
				 			<div class="side_table">
								<%= render "#{partial.name.downcase}s/#{partial.name.downcase}_partial" %>
							</div>
						</div>
					<% end %>
			<% end %>
		<% end %>
	</div>

<% end %>

app/views/shared/quick_partial_view.html.erb
<%= content_tag :h2, "#{@model_name} Partial", class: "partial_title" %>
<%= content_tag :h3, "If you would like this partial to show up on a specific page, click on that page link below and check '#{@model_name}' under 'Partials to be displayed'", class: "partial_description" %>
<%= content_tag :h3, "Page Links", class: "partial_description" %>
<% Page.all.each do |page| %>
	<%= content_tag :div, link_to( "#{page.title} page", "pages/#{page.slug}/edit"), class: "partial_link" %>
<% end %>

<br class="clear" />
<%= render "#{@model_name.downcase}s/#{@model_name.downcase}_partial" %>