config/routes.rb
Church::Application.routes.draw do
  devise_for :users, path_names: {sign_in: 'login', sign_out: 'logout'}, :controllers => { :registrations => "users" }


  mount Ckeditor::Engine => '/ckeditor'

	# mount Ckeditor::Engine => '/ckeditor'
  # match "users/search", :to => "users#search"
  devise_scope :user do  
    match "/users/search" => "users#search" 
    match "/users" => "users#index"
    match "users/:id/user_prayer_list", :to => "users#user_prayer_list", :as => "user_prayer_list"
    resources :users
  end
  resources :roles
  resources :users do 
    collection { post :sort }
  end
  resources :profiles
  resources :links
  resources :partials
  resources :categories
  resources :prayers 
  resources :affiliations
  resources :references
  resources :scriptures



  #partials
  match "announcement_partial", :to => "announcements#announcement_partial"
  match "blog_partial", :to => "blogs#blog_partial"
  match "event_partial", :to => "events#event_partial"
  match "prayer_partial", :to => "prayers#prayer_partial"


  # announcements
  match 'announcements/:id/hide', to: 'announcements#hide', as: 'hide_announcement'
  resources :announcements do
    collection { post :sort }
  end
  match "announcements/:id/announcement_status", to: "announcements#announcement_status", as: "announcement_status"
  match "announcements/:id/announcement_starts_at", to: "announcements#announcement_starts_at", as: "announcement_starts_at"
  match "announcements/:id/announcement_ends_at", to: "announcements#announcement_ends_at", as: "announcement_ends_at"
  
  # blogs
  resources :blogs do
    resources :comments
    collection { post :sort }
  end
  match 'blogs/:id/blog_status', to: 'blogs#blog_status', as: 'blog_status'
  match "blogs/:id/blog_starts_at", to: "blogs#blog_starts_at", as: "blog_starts_at"
  match "blogs/:id/blog_ends_at", to: "blogs#blog_ends_at", as: "blog_ends_at"
  
  # events
  resources :events do
    collection { post :sort }
  end
  match 'events/:id/event_status', to: 'events#event_status', as: 'event_status'
  match "events/:id/event_starts_at", to: "events#event_starts_at", as: "event_starts_at"
  match "events/:id/event_ends_at", to: "events#event_ends_at", as: "event_ends_at"

  # pages
  resources :pages do
    collection { post :sort }
    member { put :link, :status }
  end
  # match 'pages/:id/status', to: 'pages#status', as: 'status'

  # supermodels
  resources :supermodels do
    collection { post :sort }
  end
  match "supermodels/:id/model_status", :to => "supermodels#model_status", :as => "model_status"

  match 'dashboard', :to => 'static_pages#dashboard'
  
  root :to => "pages#show", :id => 'home'
end

app/models/event.rb
class Event < ActiveRecord::Base
  attr_accessible :title, :slug, :body, :event_start, :event_end, :featured
  attr_accessible :starts_at, :ends_at, :current_state, :position

	before_create :make_slug, :set_position

  validates_presence_of :title, :body
	validates_uniqueness_of :title


	include MyDateFormats

	scope :featured, where(:featured => true)

	private

	def make_slug
    self.slug = self.title.downcase.gsub(/[^a-z1-9]+/, '-').chomp('-')
  end

  def set_position
    self.position = (Describe.new(Event).published.count)+1
  end	
end

app/controllers/events_controller.rb
 class EventsController < ApplicationController 
  layout :resolve_layout
  load_and_authorize_resource

  def index
    reset_current_state(Event)
    all_event_states
    @events = Event.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @events }
    end
  end
  
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @event }
    end
  end

   def event_partial
    reset_current_state(Event)
    @events_partial = Describe.new(Event).partial
    @model_name = "Event"
    render 'shared/quick_partial_view', model_name: @model_name
  end

  def new
    @event = Event.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @event }
    end
  end

 
  def edit
   
  end

  def create
    @event = Event.new(params[:event])
    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'event was successfully created.' }
        format.json { render json: @event, status: :created, location: @event }
      else
        format.html { render action: "new" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

 
  def update
    all_event_states
    position = params[:event][:position]
    current_state = params[:event][:current_state]
    published = Status.find_by_status_name("published").id
    if (!current_state ==  published) 
      @event.position = nil
    end
    respond_to do |format|
      if @event.update_attributes(params[:event])
        format.html { redirect_to @event, notice: 'event was successfully updated.' }
        format.js { @event }
      else
        format.html { render action: "edit" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end

  def sort
    all_event_states
    params[:event].each_with_index do |id, index|
      Event.update_all({position: index+1}, {id: id})
    end
    render "update.js"
  end

  def event_status
    all_event_states
    current_state = params[:event][:current_state]
    total_published = @published_events.count
    published = Status.find_by_status_name("published").id
    if (current_state ==  published) 
      @event.update_attributes({current_state: current_state, position: total_published + 1})
    else
      @event.update_attributes({current_state: current_state, position: nil })
    end

    @published_events.each_with_index do |id, index|
      @published_events.update_all({position: index+1}, {id: id})
    end
    render "update.js"
    
  end

  def event_starts_at
    all_event_states
    starts_at = params[:event][:starts_at]
    current_state = params[:event][:current_state]
    total_published = @published_events.count

    @event.update_attributes({starts_at: starts_at})
    published = Status.find_by_status_name("published").id
    if (current_state ==  published) 
      @published_events.each_with_index do |id, index|
        @published_events.update_all({position: index+1}, {id: id})
      end
    end
    
    all_event_states
    render "update.js"
  end

  def event_ends_at
    all_event_states
    ends_at = params[:event][:ends_at]
    current_state = params[:event][:current_state]
    total_published = @published_events.count
    
    @event.update_attributes({ends_at: ends_at})
    published = Status.find_by_status_name("published").id
    if (current_state ==  published) 
      @published_events.each_with_index do |id, index|
        @published_events.update_all({position: index+1}, {id: id})
      end
    end
    all_event_states
    render "update.js"
    
  end

  def all_event_states
    @published_events = Describe.new(Event).published
    @scheduled_events = Describe.new(Event).scheduled
    @draft_events = Describe.new(Event).draft
  end
end

app/views/events/_event.html.erb
<%= content_tag_for :li, event do %>
	<%= content_tag :span, handle_if_published(event), class: "handle" %>
	<ul class="instance_detail">
		<div class="event_details">
			<%= content_tag :li, event.title, class: "title"  %>
			<!-- dynamic form for picking event status -->
			<%= form_for event, :html => {:class => 'event_ajax_edit'}, :url => {controller: "events", action: "event_status", id: event.id }, remote: true do |a| %>
					<%= collection_select(:event, :current_state, Status.all, :id, :status_name, option = { :selected => event.current_state}) %>
			<% end %>

			<%= content_tag :li, position_if_published(event), class: "page_position" %>
			<!-- dynamic form for picking starts_at -->
			<%= form_for event, :html => {:class=> "event_ajax_starts_at"}, :url => {controller: "events", action: "event_starts_at", id: event.id }, :params => [:event], remote: true do |a| %>
				<%= a.text_field :starts_at, :id => "message_#{event.id}_starts_at", :class => "event_message_starts_at" %>
			<% end %>
			<%= content_tag :li, Describe.new(Event).starts_at(event.id), class: "starts_at_date at_date #{check_if_draft(event)}", id: "message_#{event.id}_starts_at_text"  %>

			<!-- dynamic form for picking ends_at -->
			<%= form_for event, :html => {:class=> "event_ajax_ends_at"}, :url => {controller: "events", action: "event_ends_at", id: event.id }, :params => [:event], remote: true do |a| %>
				<%= a.text_field :ends_at, :id => "message_#{event.id}_start_at", :class => "event_message_ends_at" %>
			<% end %>
			<%= content_tag :li, Describe.new(Event).ends_at(event.id), class: "ends_at_date at_date #{check_if_draft(event)}", id: "message_#{event.id}_ends_at_text"  %>

		</div>
		
		<%= render "shared/crud_btns_without_view", object: event %>
		
		<div class="event_message">
			<%= content_tag :li, raw(event.body), class: "message"  %>
		</div>
	</ul>
	<br class="clear"/>

<% end %>

app/views/events/_event_partial.html.erb
<br class="clear"/>
<div class="event_partial_container">
<% @events_partial.each do |event| %>
	<%= content_tag_for :div, event, class: "event_in_partial" do %>
		<%= content_tag :li, event.starts_at, class: "event_title"  %>

		<%= content_tag :li, raw(event.title), class: "event_title"  %>
		<%= content_tag :li, raw(event.body), class: "event_body"  %>
	<% end %>
<% end %>
<br class="clear"/>
</div>

app/views/events/_form.html.erb
<script>
$(document).ready(function() { 

  $(".edit_event select").change(function() {
    cur_value = $(this).children('option:selected').text();
  })

  $("#scheduled_status").hide()

})

</script> 
  <%= form_for(@event) do |f| %> 
    <%= render 'shared/errors', object: @event %>
    <div class="field">
      <%= f.label :title %><br />
      <%= f.text_field :title %>
    </div>

    <div class="field">
      <%= f.label :body %><br />
      <%= f.text_area :body, :class => 'ckeditor' %>
    </div>
     <div class="field schedule_fields">
      <%= f.label :current_state %>
      <%= collection_select(:event, :current_state, Status.all, :id, :status_name, option = { :selected => @event.current_state}) %>
    </div>
    <div class="schedule_container">
      <div class="field schedule_fields">
        <%= f.label :starts_at %>
        <% if @event.starts_at %>
          <%= f.text_field :starts_at, :class => "datepicker", :value => Describe.new(Event).starts_at(@event.id) %>
        <% else %>
          <%= f.text_field :starts_at %>
        <% end %>
      </div>
      <div class="field schedule_fields">
        <%= f.label :ends_at %>
        <% if @event.ends_at %>
          <%= f.text_field :ends_at, :class => "datepicker", :value => Describe.new(Event).ends_at(event.id) %>
        <% else %>
          <%= f.text_field :ends_at %>
        <% end %>
      </div>
    </div>

   

    <% if can? :edit, Event %>
      <div class="field schedule_out">
        <%= f.label :featured, "Feature in Sidebar?" %><br />
        <%= f.select(:featured, [["featured event", true], ["non-featured event", false]]) %>
      </div>
    <% end %>

    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form' %>

app/views/events/index.html.erb
  
<h1>Events</h1>
<div class="column_title pages">
	<%= content_tag :p, link_to("+ New", new_event_path), class: "new_instance_button" %>
	<ul>
		<li class="title">Title</li>
		<li>Status</li>
		<li class="in announce_in">Go Live</li>
		<li class="out">Expires On</li>
	</ul>
	
</div>

<ul class="model_table eventStatus" id="published_events" data-update-url="<%= sort_events_url %>">
	<%= content_tag :h3, "Published events (#{@published_events.count})" %>
	<%= render @published_events %>
</ul>

<ul class="model_table eventStatus" id="scheduled_events" data-update-url="<%= sort_events_url %>">
	<%= content_tag :h3, "Scheduled events (#{@scheduled_events.count})" %>
	<%= render @scheduled_events %>
</ul>

<ul class="model_table eventStatus" id="draft_events" data-update-url="<%= sort_events_url %>">
	<%= content_tag :h3, "Draft events (#{@draft_events.count})" %>
	<%= render @draft_events %>
</ul>

app/views/events/new.html.erb
<h1>New event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<%= content_tag :h1, @event.title %>

<%= content_tag :div, raw(@event.body) %>

<%= link_to 'Edit | ', edit_event_path(@event) if can? :edit, @event %>
<%= link_to 'Back', events_path if can? :edit, @event %>
<%= link_to '| Destroy', @event, method: :delete, data: { confirm: 'Are you sure?' } if can? :delete, @event%>

app/views/events/update.js.erb
$("#published_events").html("<%= j render @published_events %>").prepend("<h3>Published Events (<%= @published_events.count %>)")
$("#scheduled_events").html("<%= j render @scheduled_events %>").prepend("<h3>Scheduled Events (<%= @scheduled_events.count %>)")
$("#draft_events").html("<%= j render @draft_events %>").prepend("<h3>Draft Events (<%= @draft_events.count %>)")