config/routes.rb
Church::Application.routes.draw do
  devise_for :users, path_names: {sign_in: 'login', sign_out: 'logout'}, :controllers => { :registrations => "users" }


  mount Ckeditor::Engine => '/ckeditor'

	# mount Ckeditor::Engine => '/ckeditor'
  # match "users/search", :to => "users#search"
  devise_scope :user do  
    match "/users/search" => "users#search" 
    match "/users" => "users#index"
    match "users/:id/user_prayer_list", :to => "users#user_prayer_list", :as => "user_prayer_list"
    resources :users
  end
  resources :roles
  resources :users do 
    collection { post :sort }
  end
  resources :profiles
  resources :links
  resources :partials
  resources :categories
  resources :prayers 
  resources :affiliations
  resources :references
  resources :scriptures



  #partials
  match "announcement_partial", :to => "announcements#announcement_partial"
  match "blog_partial", :to => "blogs#blog_partial"
  match "event_partial", :to => "events#event_partial"
  match "prayer_partial", :to => "prayers#prayer_partial"


  # announcements
  match 'announcements/:id/hide', to: 'announcements#hide', as: 'hide_announcement'
  resources :announcements do
    collection { post :sort }
  end
  match "announcements/:id/announcement_status", to: "announcements#announcement_status", as: "announcement_status"
  match "announcements/:id/announcement_starts_at", to: "announcements#announcement_starts_at", as: "announcement_starts_at"
  match "announcements/:id/announcement_ends_at", to: "announcements#announcement_ends_at", as: "announcement_ends_at"
  
  # blogs
  resources :blogs do
    resources :comments
    collection { post :sort }
  end
  match 'blogs/:id/blog_status', to: 'blogs#blog_status', as: 'blog_status'
  match "blogs/:id/blog_starts_at", to: "blogs#blog_starts_at", as: "blog_starts_at"
  match "blogs/:id/blog_ends_at", to: "blogs#blog_ends_at", as: "blog_ends_at"
  
  # events
  resources :events do
    collection { post :sort }
  end
  match 'events/:id/event_status', to: 'events#event_status', as: 'event_status'
  match "events/:id/event_starts_at", to: "events#event_starts_at", as: "event_starts_at"
  match "events/:id/event_ends_at", to: "events#event_ends_at", as: "event_ends_at"

  # pages
  resources :pages do
    collection { post :sort }
    member { put :link, :status }
  end
  # match 'pages/:id/status', to: 'pages#status', as: 'status'

  # supermodels
  resources :supermodels do
    collection { post :sort }
  end
  match "supermodels/:id/model_status", :to => "supermodels#model_status", :as => "model_status"

  match 'dashboard', :to => 'static_pages#dashboard'
  
  root :to => "pages#show", :id => 'home'
end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name, :scripture_list, :scripture_ids

  has_and_belongs_to_many :scriptures

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  layout :resolve_layout
  before_filter :load_category, :only => [:show, :edit, :update, :destroy] 

  authorize_resource
  def index
    @categories = Category.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @categories }
    end
  end


  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @category }
    end
  end


  def new
    @category = Category.new
    @scriptures = Scripture.all
    @category.scripture_list = []
    respond_to do |format|
      format.html
    end
  end


  def edit
    @scriptures = Scripture.all
    
  end


  def create
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
        format.html { redirect_to categories_path}
      else
        format.html { render action: "new" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to categories_path, notice: 'Category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url }
      format.js
    end
  end

  def load_category
    @category = Category.find(params[:id])
    rescue_code
  end

end

app/views/categories/_form.html.erb
<%= form_for @category do |f| %> 
	<%= render 'shared/errors', object: @category %> 
	<div class="field">
		<%= f.label :name %>
		<%= f.text_field :name %>
	</div>

	<div class="field">
	    <%= f.label :scripture_ids, "Check the scriptures that go with this category" %><br />
	    <%= hidden_field_tag "category[scripture_ids][]", nil %>
    	<% @scriptures.each do |script| %>
	      <%= check_box_tag "category[scripture_ids][]", script.id, @category.scripture_ids.include?(script.id), id: dom_id(script) %>  
      	<%= label_tag dom_id(script), truncate("#{script.title} #{script.content}", :length => 95, :omission => '... (cont)'), class: "check_box_label" %><br> 

	    <% end %>
		    
	</div>
	
	<div class="actions">
		<%= f.submit %>
	</div>


<% end %>

app/views/categories/index.html.erb
	<h1>Categories</h1> 
	<div class="column_title pages">
		<%= content_tag :p, link_to("+ New", new_category_path), class: "new_instance_button" if can? :create, Category %>
		<ul>
			<li class="title">Name</li>
		</ul>
		
	</div>

	<ul class="model_table">
		<% @categories.each do |category| %>
			<li>
				<ul class="instance_detail">
					<%= content_tag :li, category.name, class:"name" %>
					
					<%= render "shared/crud_btns_without_view", object: category %>
				</ul>
				<br class="clear">
			</li>
		<% end %>
	</ul>

app/views/categories/show.html.erb
<ul class="model_table">
	<li>
		<ul class="instance_detail">
			<%= content_tag :li, @category.name, class:"name" %><br />
			<ul class="crud_buttons">

				<%= content_tag :li, link_to("edit", edit_category_path(@category)), class:"edit" if can? :update, Category %>
				
				<%= content_tag :li, link_to("delete", category_path(@category), :confirm => "are you sure?", :method => :delete ), class:"delete" if can? :destroy, Category %>
			</ul>
		</ul>
		<br class="clear">
	</li>
	<br />

	<%= content_tag :li, link_to('View All categories', categories_path) %>
</ul>